name: Deploy to AWS EKS
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest   
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Login to AWS ECR with Docker
        uses: docker/login-action@v3
        with:
          username: AWS
          password: ${{ aws ecr get-login-password }}
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: eu-north-1
        
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: app
          push: true
          tags: apollo-server:latest
